Traceback (most recent call last):
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/DeepRL-TensorFlow2-master/A3C/A3C_Continuous.py", line 239, in <module>
    main()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/DeepRL-TensorFlow2-master/A3C/A3C_Continuous.py", line 234, in main
    agent = Agent(env_name)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/DeepRL-TensorFlow2-master/A3C/A3C_Continuous.py", line 109, in __init__
    self.global_actor = Actor(
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/DeepRL-TensorFlow2-master/A3C/A3C_Continuous.py", line 31, in __init__
    self.model = self.create_model()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/DeepRL-TensorFlow2-master/A3C/A3C_Continuous.py", line 42, in create_model
    return tf.keras.models.Model(state_input, [mu_output, std_output])
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/trackable/base.py", line 205, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/engine/functional.py", line 157, in __init__
    [
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/engine/functional.py", line 158, in <listcomp>
    functional_utils.is_input_keras_tensor(t)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/engine/functional_utils.py", line 49, in is_input_keras_tensor
    return tensor.node.is_input
AttributeError: 'KerasTensor' object has no attribute 'node'