WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x14db05e10> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x14db06050> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Exception in thread Exception in thread Exception in thread Thread-12Thread-10Exception in thread Thread-6:
:
Thread-13:
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
:
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    Traceback (most recent call last):
self.run()      File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()self.run()  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
self.run()      File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
self.train()          File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
Exception in thread self.train()self.train()  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 89, in train
    Thread-14
    self.train():
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 89, in train
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 89, in train
actor_loss = self.global_actor.train(
Traceback (most recent call last):
Exception in thread     actor_loss = self.global_actor.train(    Exception in thread   File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 89, in train
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Thread-11:
Traceback (most recent call last):
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 52, in train
Thread-8:
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Traceback (most recent call last):
    actor_loss = self.global_actor.train(
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 52, in train
actor_loss = self.global_actor.train(    self.run()  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.opt.apply_gradients(zip(grads, self.model.trainable_variables))  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 52, in train
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 52, in train
self.opt.apply_gradients(zip(grads, self.model.trainable_variables))    self.run()
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 738, in apply_gradients
self.run()    self.run()
    self.opt.apply_gradients(zip(grads, self.model.trainable_variables))
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 738, in apply_gradients
self.opt.apply_gradients(zip(grads, self.model.trainable_variables))  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
self.train()  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
return tf.__internal__.distribute.interim.maybe_merge_call(
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 738, in apply_gradients
        self.train()return tf.__internal__.distribute.interim.maybe_merge_call(  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 89, in train
self.train()  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/merge_call_interim.py", line 51, in maybe_merge_call
self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 89, in train
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 738, in apply_gradients
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 89, in train
    return fn(strategy, *args, **kwargs)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 797, in _distributed_apply
return tf.__internal__.distribute.interim.maybe_merge_call(  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 89, in train
          File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/merge_call_interim.py", line 51, in maybe_merge_call
actor_loss = self.global_actor.train(
    actor_loss = self.global_actor.train(        update_op = distribution.extended.update(return tf.__internal__.distribute.interim.maybe_merge_call(
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/merge_call_interim.py", line 51, in maybe_merge_call
actor_loss = self.global_actor.train(actor_loss = self.global_actor.train(
      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/merge_call_interim.py", line 51, in maybe_merge_call
      File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 52, in train
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 52, in train
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2633, in update
return fn(strategy, *args, **kwargs)return fn(strategy, *args, **kwargs)      File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 52, in train
          File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 52, in train
return fn(strategy, *args, **kwargs)self.opt.apply_gradients(zip(grads, self.model.trainable_variables))self.opt.apply_gradients(zip(grads, self.model.trainable_variables))      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 797, in _distributed_apply
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 797, in _distributed_apply
self.opt.apply_gradients(zip(grads, self.model.trainable_variables))
          File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 797, in _distributed_apply
return self._update(var, fn, args, kwargs, group)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 738, in apply_gradients
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 738, in apply_gradients
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 738, in apply_gradients
self.opt.apply_gradients(zip(grads, self.model.trainable_variables))update_op = distribution.extended.update(update_op = distribution.extended.update(
    update_op = distribution.extended.update(
    return tf.__internal__.distribute.interim.maybe_merge_call(
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3706, in _update
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 738, in apply_gradients
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2633, in update
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2633, in update
return tf.__internal__.distribute.interim.maybe_merge_call(  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2633, in update
    return tf.__internal__.distribute.interim.maybe_merge_call(      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/merge_call_interim.py", line 51, in maybe_merge_call
    return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)    return self._update(var, fn, args, kwargs, group)return tf.__internal__.distribute.interim.maybe_merge_call(return self._update(var, fn, args, kwargs, group)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/merge_call_interim.py", line 51, in maybe_merge_call
return self._update(var, fn, args, kwargs, group)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3712, in _update_non_slot
return fn(strategy, *args, **kwargs)      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3706, in _update
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/merge_call_interim.py", line 51, in maybe_merge_call
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/merge_call_interim.py", line 51, in maybe_merge_call
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3706, in _update
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3706, in _update
    return fn(strategy, *args, **kwargs)              File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 797, in _distributed_apply
result = fn(*args, **kwargs)        return fn(strategy, *args, **kwargs)
return fn(strategy, *args, **kwargs)return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)
return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 797, in _distributed_apply
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 595, in wrapper
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 797, in _distributed_apply
update_op = distribution.extended.update(  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 797, in _distributed_apply
      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3712, in _update_non_slot
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3712, in _update_non_slot
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3712, in _update_non_slot
Exception in thread     update_op = distribution.extended.update(                      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2633, in update
Thread-15update_op = distribution.extended.update(
update_op = distribution.extended.update(return func(*args, **kwargs)result = fn(*args, **kwargs)result = fn(*args, **kwargs)result = fn(*args, **kwargs)
:
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2633, in update
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2633, in update
Traceback (most recent call last):
return self._update(var, fn, args, kwargs, group)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2633, in update
      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 595, in wrapper
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 595, in wrapper
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 595, in wrapper
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 776, in apply_grad_to_update_var
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    return self._update(var, fn, args, kwargs, group)                          File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3706, in _update
return self._update(var, fn, args, kwargs, group)
return self._update(var, fn, args, kwargs, group)return func(*args, **kwargs)update_op = self._resource_apply_dense(grad, var, **apply_kwargs)return func(*args, **kwargs)self.run()  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3706, in _update
return func(*args, **kwargs)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3706, in _update
          File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3706, in _update
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 776, in apply_grad_to_update_var
return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adam.py", line 177, in _resource_apply_dense
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 776, in apply_grad_to_update_var
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 776, in apply_grad_to_update_var
return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)
        Exception in thread
      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3712, in _update_non_slot
update_op = self._resource_apply_dense(grad, var, **apply_kwargs)return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)Thread-7return tf.raw_ops.ResourceApplyAdam(update_op = self._resource_apply_dense(grad, var, **apply_kwargs)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3712, in _update_non_slot
update_op = self._resource_apply_dense(grad, var, **apply_kwargs)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3712, in _update_non_slot
self.train()
:
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adam.py", line 177, in _resource_apply_dense
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3712, in _update_non_slot
    Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adam.py", line 177, in _resource_apply_dense
result = fn(*args, **kwargs)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adam.py", line 177, in _resource_apply_dense
result = fn(*args, **kwargs)  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 89, in train
    result = fn(*args, **kwargs)      File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    return tf.raw_ops.ResourceApplyAdam(
result = fn(*args, **kwargs)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 595, in wrapper
return tf.raw_ops.ResourceApplyAdam(return f(**kwargs)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 595, in wrapper
return tf.raw_ops.ResourceApplyAdam(
actor_loss = self.global_actor.train(  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 595, in wrapper
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/ops/gen_training_ops.py", line 1427, in resource_apply_adam
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 595, in wrapper
      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
self.run()return func(*args, **kwargs)return func(*args, **kwargs)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 52, in train
    return func(*args, **kwargs)
        return f(**kwargs)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 776, in apply_grad_to_update_var
    return func(*args, **kwargs)return f(**kwargs)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 776, in apply_grad_to_update_var
_ops.raise_from_not_ok_status(e, name)return f(**kwargs)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 776, in apply_grad_to_update_var
self.opt.apply_gradients(zip(grads, self.model.trainable_variables))
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/ops/gen_training_ops.py", line 1427, in resource_apply_adam
self.train()  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 776, in apply_grad_to_update_var
    update_op = self._resource_apply_dense(grad, var, **apply_kwargs)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/ops/gen_training_ops.py", line 1427, in resource_apply_adam
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
update_op = self._resource_apply_dense(grad, var, **apply_kwargs)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/ops/gen_training_ops.py", line 1427, in resource_apply_adam
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 738, in apply_gradients
    update_op = self._resource_apply_dense(grad, var, **apply_kwargs)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 89, in train
        _ops.raise_from_not_ok_status(e, name)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adam.py", line 177, in _resource_apply_dense
update_op = self._resource_apply_dense(grad, var, **apply_kwargs)_ops.raise_from_not_ok_status(e, name)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adam.py", line 177, in _resource_apply_dense
    return tf.__internal__.distribute.interim.maybe_merge_call(    _ops.raise_from_not_ok_status(e, name)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adam.py", line 177, in _resource_apply_dense
raise core._status_to_exception(e) from None  # pylint: disable=protected-access
actor_loss = self.global_actor.train(
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adam.py", line 177, in _resource_apply_dense
return tf.raw_ops.ResourceApplyAdam(  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
return tf.raw_ops.ResourceApplyAdam(  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/merge_call_interim.py", line 51, in maybe_merge_call
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
return tf.raw_ops.ResourceApplyAdam(
        tensorflow.python.framework.errors_impl
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 52, in train
      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
raise core._status_to_exception(e) from None  # pylint: disable=protected-accessreturn tf.raw_ops.ResourceApplyAdam(.  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
raise core._status_to_exception(e) from None  # pylint: disable=protected-accessreturn fn(strategy, *args, **kwargs)      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
raise core._status_to_exception(e) from None  # pylint: disable=protected-access
    return f(**kwargs)
self.opt.apply_gradients(zip(grads, self.model.trainable_variables))
tensorflow.python.framework.errors_impl  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/ops/gen_training_ops.py", line 1427, in resource_apply_adam
InvalidArgumentError
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
    return f(**kwargs)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 797, in _distributed_apply
tensorflow.python.framework.errors_impl.: tensorflow.python.framework.errors_implreturn f(**kwargs)
              File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 738, in apply_gradients
.InvalidArgumentError.Cannot assign a device for operation ResourceApplyAdam: Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceApplyAdam: CPU
_Arg: GPU CPU
Colocation members, user-requested devices, and framework assigned devices, if any:
  var (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  m (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  v (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceApplyAdam (ResourceApplyAdam) /job:localhost/replica:0/task:0/device:GPU:0
Op: ResourceApplyAdam
Node attrs: use_locking=true, T=DT_DOUBLE, use_nesterov=false
Registered kernels:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
	 [[{{node ResourceApplyAdam}}]] [Op:ResourceApplyAdam]
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/ops/gen_training_ops.py", line 1427, in resource_apply_adam
return f(**kwargs)_ops.raise_from_not_ok_status(e, name)update_op = distribution.extended.update(InvalidArgumentError: InvalidArgumentError
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/ops/gen_training_ops.py", line 1427, in resource_apply_adam
: Cannot assign a device for operation ResourceApplyAdam: Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceApplyAdam: CPU
_Arg: GPU CPU
Colocation members, user-requested devices, and framework assigned devices, if any:
  var (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  m (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  v (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceApplyAdam (ResourceApplyAdam) /job:localhost/replica:0/task:0/device:GPU:0
Op: ResourceApplyAdam
Node attrs: use_locking=true, T=DT_DOUBLE, use_nesterov=false
Registered kernels:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
	 [[{{node ResourceApplyAdam}}]] [Op:ResourceApplyAdam]:     return tf.__internal__.distribute.interim.maybe_merge_call(  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/ops/gen_training_ops.py", line 1427, in resource_apply_adam
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2633, in update
    Cannot assign a device for operation ResourceApplyAdam: Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceApplyAdam: CPU
_Arg: GPU CPU
Colocation members, user-requested devices, and framework assigned devices, if any:
  var (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  m (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  v (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceApplyAdam (ResourceApplyAdam) /job:localhost/replica:0/task:0/device:GPU:0
Op: ResourceApplyAdam
Node attrs: use_locking=true, T=DT_DOUBLE, use_nesterov=false
Registered kernels:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
	 [[{{node ResourceApplyAdam}}]] [Op:ResourceApplyAdam]
Cannot assign a device for operation ResourceApplyAdam: Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceApplyAdam: CPU
_Arg: GPU CPU
Colocation members, user-requested devices, and framework assigned devices, if any:
  var (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  m (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  v (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceApplyAdam (ResourceApplyAdam) /job:localhost/replica:0/task:0/device:GPU:0
Op: ResourceApplyAdam
Node attrs: use_locking=true, T=DT_DOUBLE, use_nesterov=false
Registered kernels:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
	 [[{{node ResourceApplyAdam}}]] [Op:ResourceApplyAdam]
_ops.raise_from_not_ok_status(e, name)
_ops.raise_from_not_ok_status(e, name)      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/merge_call_interim.py", line 51, in maybe_merge_call
_ops.raise_from_not_ok_status(e, name)return self._update(var, fn, args, kwargs, group)    raise core._status_to_exception(e) from None  # pylint: disable=protected-access  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
return fn(strategy, *args, **kwargs)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3706, in _update
tensorflow.python.framework.errors_impl        raise core._status_to_exception(e) from None  # pylint: disable=protected-access  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 797, in _distributed_apply
.raise core._status_to_exception(e) from None  # pylint: disable=protected-access    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
InvalidArgumentError
    return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)
tensorflow.python.framework.errors_impl: tensorflow.python.framework.errors_implupdate_op = distribution.extended.update(
tensorflow.python.framework.errors_impl.Cannot assign a device for operation ResourceApplyAdam: Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceApplyAdam: CPU
_Arg: GPU CPU
Colocation members, user-requested devices, and framework assigned devices, if any:
  var (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  m (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  v (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceApplyAdam (ResourceApplyAdam) /job:localhost/replica:0/task:0/device:GPU:0
Op: ResourceApplyAdam
Node attrs: use_locking=true, T=DT_DOUBLE, use_nesterov=false
Registered kernels:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
	 [[{{node ResourceApplyAdam}}]] [Op:ResourceApplyAdam].
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3712, in _update_non_slot
.InvalidArgumentError
InvalidArgumentError  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2633, in update
InvalidArgumentError: :     : Cannot assign a device for operation ResourceApplyAdam: Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceApplyAdam: CPU
_Arg: GPU CPU
Colocation members, user-requested devices, and framework assigned devices, if any:
  var (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  m (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  v (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceApplyAdam (ResourceApplyAdam) /job:localhost/replica:0/task:0/device:GPU:0
Op: ResourceApplyAdam
Node attrs: use_locking=true, T=DT_DOUBLE, use_nesterov=false
Registered kernels:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
	 [[{{node ResourceApplyAdam}}]] [Op:ResourceApplyAdam]Cannot assign a device for operation ResourceApplyAdam: Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceApplyAdam: CPU
_Arg: GPU CPU
Colocation members, user-requested devices, and framework assigned devices, if any:
  var (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  m (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  v (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceApplyAdam (ResourceApplyAdam) /job:localhost/replica:0/task:0/device:GPU:0
Op: ResourceApplyAdam
Node attrs: use_locking=true, T=DT_DOUBLE, use_nesterov=false
Registered kernels:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
	 [[{{node ResourceApplyAdam}}]] [Op:ResourceApplyAdam]    result = fn(*args, **kwargs)Cannot assign a device for operation ResourceApplyAdam: Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceApplyAdam: CPU
_Arg: GPU CPU
Colocation members, user-requested devices, and framework assigned devices, if any:
  var (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  m (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  v (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceApplyAdam (ResourceApplyAdam) /job:localhost/replica:0/task:0/device:GPU:0
Op: ResourceApplyAdam
Node attrs: use_locking=true, T=DT_DOUBLE, use_nesterov=false
Registered kernels:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
	 [[{{node ResourceApplyAdam}}]] [Op:ResourceApplyAdam]
return self._update(var, fn, args, kwargs, group)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 595, in wrapper
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3706, in _update
    return func(*args, **kwargs)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 776, in apply_grad_to_update_var
    return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)
update_op = self._resource_apply_dense(grad, var, **apply_kwargs)  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3712, in _update_non_slot
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adam.py", line 177, in _resource_apply_dense
    result = fn(*args, **kwargs)
return tf.raw_ops.ResourceApplyAdam(  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 595, in wrapper
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
        return func(*args, **kwargs)return f(**kwargs)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 776, in apply_grad_to_update_var
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/ops/gen_training_ops.py", line 1427, in resource_apply_adam
    update_op = self._resource_apply_dense(grad, var, **apply_kwargs)
      File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adam.py", line 177, in _resource_apply_dense
_ops.raise_from_not_ok_status(e, name)    return tf.raw_ops.ResourceApplyAdam(
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
    return f(**kwargs)
raise core._status_to_exception(e) from None  # pylint: disable=protected-access  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/ops/gen_training_ops.py", line 1427, in resource_apply_adam
tensorflow.python.framework.errors_impl.InvalidArgumentError:     Cannot assign a device for operation ResourceApplyAdam: Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceApplyAdam: CPU
_Arg: GPU CPU
Colocation members, user-requested devices, and framework assigned devices, if any:
  var (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  m (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  v (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceApplyAdam (ResourceApplyAdam) /job:localhost/replica:0/task:0/device:GPU:0
Op: ResourceApplyAdam
Node attrs: use_locking=true, T=DT_DOUBLE, use_nesterov=false
Registered kernels:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
	 [[{{node ResourceApplyAdam}}]] [Op:ResourceApplyAdam]_ops.raise_from_not_ok_status(e, name)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation ResourceApplyAdam: Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceApplyAdam: CPU
_Arg: GPU CPU
Colocation members, user-requested devices, and framework assigned devices, if any:
  var (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  m (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  v (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceApplyAdam (ResourceApplyAdam) /job:localhost/replica:0/task:0/device:GPU:0
Op: ResourceApplyAdam
Node attrs: use_locking=true, T=DT_DOUBLE, use_nesterov=false
Registered kernels:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
	 [[{{node ResourceApplyAdam}}]] [Op:ResourceApplyAdam]
1/1 [==============================] - 0s 227ms/step
1/1 [==============================] - 0s 191ms/step
1/1 [==============================] - 0s 200ms/step
1/1 [==============================] - 0s 195ms/step
1/1 [==============================] - 0s 171ms/step
1/1 [==============================] - 0s 188ms/step
1/1 [==============================] - 0s 213ms/step
1/1 [==============================] - 0s 171ms/step
1/1 [==============================] - 0s 224ms/step
1/1 [==============================] - 0s 190ms/step
1/1 [==============================] - 0s 69ms/step
1/1 [==============================] - 0s 11ms/step
1/1 [==============================] - 0s 12ms/step
1/1 [==============================] - 0s 18ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 17ms/step
1/1 [==============================] - 0s 23ms/step
1/1 [==============================] - 0s 12ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 18ms/step
1/1 [==============================] - 0s 27ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 18ms/step
1/1 [==============================] - 0s 25ms/step
1/1 [==============================] - 0s 16ms/step
1/1 [==============================] - 0s 12ms/step
1/1 [==============================] - 0s 18ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 26ms/step
1/1 [==============================] - 0s 26ms/step
1/1 [==============================] - 0s 23ms/step
1/1 [==============================] - 0s 27ms/step
1/1 [==============================] - 0s 22ms/step
1/1 [==============================] - 0s 25ms/step
1/1 [==============================] - 0s 22ms/step
1/1 [==============================] - 0s 16ms/step
1/1 [==============================] - 0s 23ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 12ms/step
1/1 [==============================] - 0s 22ms/step
1/1 [==============================] - 0s 17ms/step
1/1 [==============================] - 0s 18ms/step
1/1 [==============================] - 0s 24ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 25ms/step
1/1 [==============================] - 0s 18ms/step
1/1 [==============================] - 0s 146ms/step
1/1 [==============================] - 0s 16ms/step
1/1 [==============================] - 0s 24ms/step
1/1 [==============================] - 0s 128ms/step
1/1 [==============================] - 0s 137ms/step
1/1 [==============================] - 0s 115ms/step
1/1 [==============================] - 0s 80ms/step
1/1 [==============================] - 0s 119ms/step
1/1 [==============================] - 0s 18ms/step
1/1 [==============================] - 0s 118ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 23ms/step
1/1 [==============================] - 0s 134ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 16ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 89ms/step
1/1 [==============================] - 0s 104ms/step
1/1 [==============================] - 0s 12ms/step
1/1 [==============================] - 0s 16ms/step