Exception in thread Thread-6Exception in thread Exception in thread :
Thread-7Exception in thread Thread-9Exception in thread Traceback (most recent call last):
Exception in thread Exception in thread Thread-12:
Traceback (most recent call last):
Thread-8Exception in thread Thread-15:
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Thread-11:
Traceback (most recent call last):
Exception in thread Exception in thread :
Traceback (most recent call last):
:
Traceback (most recent call last):
Thread-10:
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Thread-13  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Traceback (most recent call last):
Traceback (most recent call last):
    :
Traceback (most recent call last):
Thread-14:
Traceback (most recent call last):
          File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    :
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()self.run()    self.run()
    self.run()  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 112, in run
    self.run()
self.run()  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 112, in run
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 112, in run
self.run()  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 112, in run
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 112, in run
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 112, in run
      File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 112, in run
self.train()  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 112, in run
    self.train()
self.train()  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 112, in run
self.train()
        self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 112, in run
self.train()  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 54, in train
    self.train()self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 54, in train
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 54, in train
      File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 54, in train
self.train()
      File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 54, in train
        self.train()  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 54, in train
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 54, in train
      File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 54, in train
while self.max_episodes >= CUR_EPISODE:while self.max_episodes >= CUR_EPISODE:while self.max_episodes >= CUR_EPISODE:
      File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 54, in train
while self.max_episodes >= CUR_EPISODE:
      File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 54, in train
while self.max_episodes >= CUR_EPISODE:
while self.max_episodes >= CUR_EPISODE:while self.max_episodes >= CUR_EPISODE:NameError    NameErrorNameErrorwhile self.max_episodes >= CUR_EPISODE:
NameError
    : while self.max_episodes >= CUR_EPISODE:: :
NameError: NameErrorNameErrorwhile self.max_episodes >= CUR_EPISODE:name 'CUR_EPISODE' is not defined
name 'CUR_EPISODE' is not definedname 'CUR_EPISODE' is not definedNameError: name 'CUR_EPISODE' is not defined: :
NameError
: name 'CUR_EPISODE' is not defined
name 'CUR_EPISODE' is not definedname 'CUR_EPISODE' is not definedNameError: :
name 'CUR_EPISODE' is not definedname 'CUR_EPISODE' is not definedname 'CUR_EPISODE' is not defined